version: '3.8'

services:
  swtest2:
    build: ./
    command: ./swtest2
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - fullstack


  db:
    image: postgres:latest
    container_name: "postgresd"
    ports:
      - "5436:5436"
    environment:
      - POSTGRES_DB=travelagency
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge
      